class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'en': {
      // Common
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'retry': 'Retry',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'close': 'Close',
      'yes': 'Yes',
      'no': 'No',
      'ok': 'OK',
      'back': 'Back',
      'next': 'Next',
      'previous': 'Previous',
      'submit': 'Submit',
      'search': 'Search',
      'filter': 'Filter',
      'sort': 'Sort',
      'refresh': 'Refresh',
      'settings': 'Settings',
      'profile': 'Profile',
      'logout': 'Logout',
      'language': 'Language',
      'select_language': 'Select Language',
      'language_changed': 'Language changed to',
      'good_morning': 'Good Morning,',
      'good_afternoon': 'Good Afternoon,',
      'good_evening': 'Good Evening,',
      'complete_your_profile': 'Complete your profile',
      'completed': 'completed',
      'update_your_profile': 'Update your profile',
      'notifications_coming_soon': 'Notifications coming soon!',

      // Auth
      'login': 'Login',
      'signup': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'forgot_password': 'Forgot Password?',
      'remember_me': 'Remember Me',
      'dont_have_account': "Don't have an account?",
      'already_have_account': 'Already have an account?',
      'login_success': 'Login successful',
      'signup_success': 'Account created successfully',
      'invalid_credentials': 'Invalid email or password',
      'password_mismatch': 'Passwords do not match',
      'weak_password': 'Password is too weak',
      'email_already_exists': 'Email already exists',

      // Login/Signup specific
      'welcome_back': 'Welcome back!',
      'email_phone': 'Email/Phone',
      'continue_with_google': 'Continue with Google',
      'create_account': 'Create Account',
      'please_fill_all_fields': 'Please fill in all fields',
      'invalid_input_format':
          'Invalid input. Please check your email/phone format.',
      'no_internet_connection':
          'No internet connection. Please check your network.',
      'connection_timeout': 'Connection timeout. Please try again.',
      'login_failed_try_again': 'Login failed. Please try again.',

      // Signup specific
      'welcome_to_hrms': 'Welcome to HRMS',
      'property_management_system': 'Property Management System',
      'mobile_hint': '01XXXXXXXXX',
      'sign_up_with_google': 'Sign up with Google',
      'smart_registration': 'Smart Registration',
      'enter_mobile_detect_role':
          'Enter your mobile number to automatically detect your role',
      'enter_mobile_number': 'Enter mobile number',
      'role_detected': 'Role Detected!',
      'found_account_database': 'We found your account in our database!',
      'role_property_owner': 'Role: Property Owner',
      'role_tenant': 'Role: Tenant',
      'choose_different_role': 'Choose Different Role',
      'continue': 'Continue',
      'please_enter_mobile': 'Please enter mobile number',
      'valid_bangladeshi_number':
          'Please enter a valid Bangladeshi number (11 digits starting with 01). +88 will be removed automatically',
      'valid_bangladeshi_number_simple':
          'Please enter a valid Bangladeshi number (11 digits starting with 01).',
      'owner_found_redirecting': 'Owner found! Redirecting to login...',
      'tenant_found_redirecting':
          'Tenant found! Redirecting to tenant registration...',
      'new_user_redirecting': 'New user! Redirecting to owner registration...',
      'please_enter_valid_mobile': 'Please enter a valid mobile number',
      'mobile_number_required': 'Mobile number is required',
      'google_signin_failed': 'Google Sign-In failed. Please try again.',
      'new_user_mobile_continue':
          'New user detected! Please enter your mobile number to continue',
      'language_changed_english': 'Language changed to English',
      'language_changed_bangla': 'ভাষা বাংলায় পরিবর্তন করা হয়েছে',

      // Why Choose HRMS
      'why_choose_hrms': 'Why Choose HRMS?',
      'property_management': 'Property Management',
      'manage_properties_efficiently': 'Manage properties efficiently',
      'tenant_management': 'Tenant Management',
      'track_tenants_details': 'Track tenants details',
      'rent_collection': 'Rent Collection',
      'automated_rent_collection': 'Automated rent collection',
      'secure_reliable': 'Secure & Reliable',
      'data_safe_with_us': 'Your data is safe with us',

      // Verification
      'verify_mobile_number': 'Verify your mobile number',
      'verify_mobile_message':
          'For security and full access, please verify your phone.',
      'verify_now': 'Verify now',
      'update': 'Update',

      // Dashboard
      'dashboard': 'Dashboard',
      'welcome': 'Welcome',
      'total_properties': 'Total Properties',
      'active_properties': 'Active Properties',
      'total_tenants': 'Total Tenants',
      'total_income': 'Total Income',
      'recent_transactions': 'Recent Transactions',
      'property_completion': 'Profile Completion',
      'subscription': 'Subscription',
      'subscription_plans': 'Subscription Plans',
      'subscription_plan': 'Subscription Plan',
      'free_plan': 'Free Plan',
      'premium_plan': 'Premium Plan',
      'expires_on': 'Expires on',
      'days_remaining': 'days remaining',
      'loading_dashboard': 'Loading dashboard...',
      'collections': 'Collections',
      'this_month': 'This Month',
      'due_amount': 'Due Amount',
      'pending': 'Pending',
      'view_all': 'View All',
      'no_recent_transactions': 'No recent transactions',
      'transaction': 'Transaction',
      'limited_features': 'Limited Features',
      'premium_features': 'Premium Features',
      'upgrade': 'Upgrade',
      'manage': 'Manage',

      // Property
      'properties': 'Properties',
      'add_property': 'Add Property',
      'edit_property': 'Edit Property',
      'property_name': 'Property Name',
      'property_address': 'Property Address',
      'property_type': 'Property Type',
      'property_status': 'Property Status',
      'rent_amount': 'Rent Amount',
      'property_details': 'Property Details',
      'property_photos': 'Property Photos',
      'active': 'Active',
      'inactive': 'Inactive',
      'maintenance': 'Maintenance',

      // Tenants
      'tenants': 'Tenants',
      'add_tenant': 'Add Tenant',
      'edit_tenant': 'Edit Tenant',
      'tenant_name': 'Tenant Name',
      'tenant_phone': 'Tenant Phone',
      'tenant_email': 'Tenant Email',
      'move_in_date': 'Move In Date',
      'move_out_date': 'Move Out Date',
      'rent_due_date': 'Rent Due Date',
      'tenant_status': 'Tenant Status',

      // Billing
      'billing': 'Billing',
      'invoices': 'Invoices',
      'payments': 'Payments',
      'create_invoice': 'Create Invoice',
      'invoice_number': 'Invoice Number',
      'invoice_date': 'Invoice Date',
      'due_date': 'Due Date',
      'amount': 'Amount',
      'status': 'Status',
      'paid': 'Paid',
      'unpaid': 'Unpaid',
      'partial': 'Partial',
      'overdue': 'Overdue',
      'payment_method': 'Payment Method',
      'cash': 'Cash',
      'bank_transfer': 'Bank Transfer',
      'mobile_banking': 'Mobile Banking',
      'check': 'Check',
      'other': 'Other',

      // Navigation
      'home': 'Home',
      'reports': 'Reports',
      'backups': 'Backups',
      'menu': 'Menu',
      'units': 'Units',
      'checkout_records': 'Checkout Records',
      'notifications': 'Notifications',
      'help_support': 'Help & Support',
      'about': 'About',
      'log_out': 'Log Out',

      // Messages
      'no_data_found': 'No data found',
      'something_went_wrong': 'Something went wrong',
      'network_error': 'Network error',
      'try_again': 'Please try again',
      'operation_successful': 'Operation successful',
      'operation_failed': 'Operation failed',
      'are_you_sure': 'Are you sure?',
      'this_action_cannot_be_undone': 'This action cannot be undone',
      'failed_to_load': 'Failed to load',
      'failed_to_save': 'Failed to save',
      'failed_to_delete': 'Failed to delete',

      // Validation
      'required_field': 'This field is required',
      'invalid_email': 'Please enter a valid email',
      'invalid_phone': 'Please enter a valid phone number',
      'password_too_short': 'Password must be at least 6 characters',
      'password_too_long': 'Password must be less than 50 characters',
      'name_too_short': 'Name must be at least 2 characters',
      'name_too_long': 'Name must be less than 100 characters',

      // Mobile verification
      'mobile_verification_title': 'Verify Mobile Number',
      'mobile_verification_message':
          'Please verify your mobile number to complete your profile',
      'mobile_verification_button': 'Verify Now',
    },

    'bn': {
      // Common
      'loading': 'লোড হচ্ছে...',
      'error': 'ত্রুটি',
      'success': 'সফল',
      'retry': 'পুনরায় চেষ্টা করুন',
      'cancel': 'বাতিল',
      'save': 'সংরক্ষণ করুন',
      'delete': 'মুছুন',
      'edit': 'সম্পাদনা করুন',
      'add': 'যোগ করুন',
      'close': 'বন্ধ করুন',
      'yes': 'হ্যাঁ',
      'no': 'না',
      'ok': 'ঠিক আছে',
      'back': 'পিছনে',
      'next': 'পরবর্তী',
      'previous': 'পূর্ববর্তী',
      'submit': 'জমা দিন',
      'search': 'অনুসন্ধান',
      'filter': 'ফিল্টার',
      'sort': 'সাজান',
      'refresh': 'রিফ্রেশ',
      'settings': 'সেটিংস',
      'profile': 'প্রোফাইল',
      'logout': 'লগআউট',
      'language': 'ভাষা',
      'select_language': 'ভাষা নির্বাচন করুন',
      'language_changed': 'ভাষা পরিবর্তন হয়েছে',
      'good_morning': 'সুপারিশ,',
      'good_afternoon': 'সুপারিশ,',
      'good_evening': 'সুপারিশ,',
      'complete_your_profile': 'আপনার প্রোফাইল সম্পূর্ণ করুন',
      'completed': 'সম্পূর্ণ',
      'update_your_profile': 'আপনার প্রোফাইল আপডেট করুন',
      'notifications_coming_soon': 'বিজ্ঞপ্তি সম্বদ্ধে আগামীতে আসছে!',

      // Auth
      'login': 'লগইন',
      'signup': 'সাইন আপ',
      'email': 'ইমেইল',
      'password': 'পাসওয়ার্ড',
      'confirm_password': 'পাসওয়ার্ড নিশ্চিত করুন',
      'forgot_password': 'পাসওয়ার্ড ভুলে গেছেন?',
      'remember_me': 'আমাকে মনে রাখুন',
      'dont_have_account': 'অ্যাকাউন্ট নেই?',
      'already_have_account': 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
      'login_success': 'সফলভাবে লগইন হয়েছে',
      'signup_success': 'অ্যাকাউন্ট সফলভাবে তৈরি হয়েছে',
      'invalid_credentials': 'ভুল ইমেইল বা পাসওয়ার্ড',
      'password_mismatch': 'পাসওয়ার্ড মিলছে না',
      'weak_password': 'পাসওয়ার্ড খুব দুর্বল',
      'email_already_exists': 'ইমেইল ইতিমধ্যে বিদ্যমান',

      // Login/Signup specific
      'welcome_back': 'স্বাগতম!',
      'email_phone': 'ইমেইল/ফোন',
      'continue_with_google': 'গুগলের সাথে চালিয়ে যান',
      'create_account': 'অ্যাকাউন্ট তৈরি করুন',
      'please_fill_all_fields': 'অনুগ্রহ করে সব ক্ষেত্র পূরণ করুন',
      'invalid_input_format':
          'অবৈধ ইনপুট। অনুগ্রহ করে আপনার ইমেইল/ফোন ফরম্যাট পরীক্ষা করুন।',
      'no_internet_connection':
          'নেটওয়ার্কের সংযোগ নেই। অনুগ্রহ করে আপনার নেটওয়ার্ক পরীক্ষা করুন।',
      'connection_timeout': 'সংযোগ টাইমআউট। অনুগ্রহ করে আবার চেষ্টা করুন।',
      'login_failed_try_again': 'লগইন ব্যর্থ। অনুগ্রহ করে আবার চেষ্টা করুন।',

      // Signup specific
      'welcome_to_hrms': 'HRMS-এ স্বাগতম',
      'property_management_system': 'সম্পত্তি ব্যবস্থাপনা সিস্টেম',
      'mobile_hint': '০১XXXXXXXXX',
      'sign_up_with_google': 'গুগলের সাথে সাইন আপ করুন',
      'smart_registration': 'স্মার্ট নিবন্ধন',
      'enter_mobile_detect_role':
          'স্বয়ংক্রিয়ভাবে আপনার ভূমিকা সনাক্ত করতে আপনার মোবাইল নম্বর দিন',
      'enter_mobile_number': 'মোবাইল নম্বর দিন',
      'role_detected': 'ভূমিকা সনাক্ত হয়েছে!',
      'found_account_database':
          'আমরা আমাদের ডেটাবেসে আপনার অ্যাকাউন্ট খুঁজে পেয়েছি!',
      'role_property_owner': 'ভূমিকা: সম্পত্তির মালিক',
      'role_tenant': 'ভূমিকা: ভাড়াটে',
      'choose_different_role': 'ভিন্ন ভূমিকা নির্বাচন করুন',
      'continue': 'চালিয়ে যান',
      'please_enter_mobile': 'অনুগ্রহ করে মোবাইল নম্বর দিন',
      'valid_bangladeshi_number':
          'অনুগ্রহ করে একটি সঠিক বাংলাদেশী নম্বর দিন (০১ দিয়ে শুরু করে ১১ অঙ্ক)। +৮৮ স্বয়ংক্রিয়ভাবে সরানো হবে',
      'valid_bangladeshi_number_simple':
          'অনুগ্রহ করে একটি সঠিক বাংলাদেশী নম্বর দিন (০১ দিয়ে শুরু করে ১১ অঙ্ক)।',
      'owner_found_redirecting':
          'মালিক পাওয়া গেছে! লগইনে পুনর্নির্দেশিত হচ্ছে...',
      'tenant_found_redirecting':
          'ভাড়াটে পাওয়া গেছে! ভাড়াটে নিবন্ধনে পুনর্নির্দেশিত হচ্ছে...',
      'new_user_redirecting':
          'নতুন ব্যবহারকারী! মালিক নিবন্ধনে পুনর্নির্দেশিত হচ্ছে...',
      'please_enter_valid_mobile': 'অনুগ্রহ করে একটি সঠিক মোবাইল নম্বর দিন',
      'mobile_number_required': 'মোবাইল নম্বর প্রয়োজন',
      'google_signin_failed':
          'গুগল সাইন-ইন ব্যর্থ। অনুগ্রহ করে আবার চেষ্টা করুন।',
      'new_user_mobile_continue':
          'নতুন ব্যবহারকারী সনাক্ত হয়েছে! অনুগ্রহ করে চালিয়ে যেতে আপনার মোবাইল নম্বর দিন',
      'language_changed_english': 'ভাষা ইংরেজিতে পরিবর্তন করা হয়েছে',
      'language_changed_bangla': 'ভাষা বাংলায় পরিবর্তন করা হয়েছে',

      // Why Choose HRMS
      'why_choose_hrms': 'কেন HRMS বেছে নেবেন?',
      'property_management': 'সম্পত্তি ব্যবস্থাপনা',
      'manage_properties_efficiently': 'সম্পত্তি দক্ষতার সাথে পরিচালনা করুন',
      'tenant_management': 'ভাড়াটে ব্যবস্থাপনা',
      'track_tenants_details': 'ভাড়াটেদের বিবরণ ট্র্যাক করুন',
      'rent_collection': 'ভাড়া সংগ্রহ',
      'automated_rent_collection': 'স্বয়ংক্রিয় ভাড়া সংগ্রহ',
      'secure_reliable': 'নিরাপদ ও নির্ভরযোগ্য',
      'data_safe_with_us': 'আপনার ডেটা আমাদের সাথে নিরাপদ',

      // Verification
      'verify_mobile_number': 'আপনার মোবাইল নম্বর যাচাই করুন',
      'verify_mobile_message':
          'নিরাপত্তা এবং সম্পূর্ণ অ্যাক্সেসের জন্য, অনুগ্রহ করে আপনার ফোন যাচাই করুন।',
      'verify_now': 'এখন যাচাই করুন',
      'update': 'আপডেট',

      // Dashboard
      'dashboard': 'ড্যাশবোর্ড',
      'welcome': 'স্বাগতম',
      'total_properties': 'মোট সম্পত্তি',
      'active_properties': 'সক্রিয় সম্পত্তি',
      'total_tenants': 'মোট ভাড়াটে',
      'total_income': 'মোট আয়',
      'recent_transactions': 'সাম্প্রতিক লেনদেন',
      'property_completion': 'প্রোফাইল সম্পূর্ণতা',
      'subscription': 'সাবস্ক্রিপশন',
      'subscription_plans': 'সাবস্ক্রিপশন প্ল্যান',
      'subscription_plan': 'সাবস্ক্রিপশন প্ল্যান',
      'free_plan': 'ফ্রি প্ল্যান',
      'premium_plan': 'প্রিমিয়াম প্ল্যান',
      'expires_on': 'মেয়াদ শেষ হবে',
      'days_remaining': 'দিন বাকি',
      'loading_dashboard': 'ড্যাশবোর্ড লোড হচ্ছে...',
      'collections': 'সংগ্রহ',
      'this_month': 'এই মাসে',
      'due_amount': 'বকেয়া পরিমাণ',
      'pending': 'অপেক্ষমান',
      'view_all': 'সব দেখুন',
      'no_recent_transactions': 'কোন সাম্প্রতিক লেনদেন নেই',
      'transaction': 'লেনদেন',
      'limited_features': 'সীমিত বৈশিষ্ট্য',
      'premium_features': 'প্রিমিয়াম বৈশিষ্ট্য',
      'upgrade': 'আপগ্রেড',
      'manage': 'ব্যবস্থাপনা',

      // Property
      'properties': 'সম্পত্তি',
      'add_property': 'সম্পত্তি যোগ করুন',
      'edit_property': 'সম্পত্তি সম্পাদনা করুন',
      'property_name': 'সম্পত্তির নাম',
      'property_address': 'সম্পত্তির ঠিকানা',
      'property_type': 'সম্পত্তির ধরন',
      'property_status': 'সম্পত্তির অবস্থা',
      'rent_amount': 'ভাড়ার পরিমাণ',
      'property_details': 'সম্পত্তির বিবরণ',
      'property_photos': 'সম্পত্তির ছবি',
      'active': 'সক্রিয়',
      'inactive': 'নিষ্ক্রিয়',
      'maintenance': 'রক্ষণাবেক্ষণ',

      // Tenants
      'tenants': 'ভাড়াটে',
      'add_tenant': 'ভাড়াটে যোগ করুন',
      'edit_tenant': 'ভাড়াটে সম্পাদনা করুন',
      'tenant_name': 'ভাড়াটের নাম',
      'tenant_phone': 'ভাড়াটের ফোন',
      'tenant_email': 'ভাড়াটের ইমেইল',
      'move_in_date': 'ভাড়া নেওয়ার তারিখ',
      'move_out_date': 'ভাড়া ছাড়ার তারিখ',
      'rent_due_date': 'ভাড়া পরিশোধের তারিখ',
      'tenant_status': 'ভাড়াটের অবস্থা',

      // Billing
      'billing': 'বিলিং',
      'invoices': 'ইনভয়েস',
      'payments': 'পেমেন্ট',
      'create_invoice': 'ইনভয়েস তৈরি করুন',
      'invoice_number': 'ইনভয়েস নম্বর',
      'invoice_date': 'ইনভয়েসের তারিখ',
      'due_date': 'শেষ তারিখ',
      'amount': 'পরিমাণ',
      'status': 'অবস্থা',
      'paid': 'পরিশোধিত',
      'unpaid': 'অপরিশোধিত',
      'partial': 'আংশিক',
      'overdue': 'মেয়াদোত্তীর্ণ',
      'payment_method': 'পেমেন্ট পদ্ধতি',
      'cash': 'নগদ',
      'bank_transfer': 'ব্যাংক ট্রান্সফার',
      'mobile_banking': 'মোবাইল ব্যাংকিং',
      'check': 'চেক',
      'other': 'অন্যান্য',

      // Navigation
      'home': 'হোম',
      'reports': 'রিপোর্ট',
      'backups': 'ব্যাকআপ',
      'menu': 'মেনু',
      'units': 'একক',
      'checkout_records': 'চেকআউট রেকর্ড',
      'notifications': 'বিজ্ঞপ্তি',
      'help_support': 'সহায়তা & সমর্থন',
      'about': 'বিষয়',
      'log_out': 'লগ আউট',

      // Messages
      'no_data_found': 'কোন ডেটা পাওয়া যায়নি',
      'something_went_wrong': 'কিছু ভুল হয়েছে',
      'network_error': 'নেটওয়ার্ক ত্রুটি',
      'try_again': 'অনুগ্রহ করে আবার চেষ্টা করুন',
      'operation_successful': 'অপারেশন সফল',
      'operation_failed': 'অপারেশন ব্যর্থ',
      'are_you_sure': 'আপনি কি নিশ্চিত?',
      'this_action_cannot_be_undone': 'এই কাজটি পূর্বাবস্থায় ফেরানো যাবে না',
      'failed_to_load': 'লোড করতে ব্যর্থ',
      'failed_to_save': 'সংরক্ষণ করতে ব্যর্থ',
      'failed_to_delete': 'মুছতে ব্যর্থ',

      // Validation
      'required_field': 'এই ক্ষেত্রটি প্রয়োজন',
      'invalid_email': 'অনুগ্রহ করে একটি সঠিক ইমেইল দিন',
      'invalid_phone': 'অনুগ্রহ করে একটি সঠিক ফোন নম্বর দিন',
      'password_too_short': 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষর হতে হবে',
      'password_too_long': 'পাসওয়ার্ড ৫০ অক্ষরের কম হতে হবে',
      'name_too_short': 'নাম কমপক্ষে ২ অক্ষর হতে হবে',
      'name_too_long': 'নাম ১০০ অক্ষরের কম হতে হবে',

      // Mobile verification
      'mobile_verification_title': 'মোবাইল নম্বর যাচাই করুন',
      'mobile_verification_message':
          'আপনার প্রোফাইল সম্পূর্ণ করতে অনুগ্রহ করে আপনার মোবাইল নম্বর যাচাই করুন',
      'mobile_verification_button': 'এখনই যাচাই করুন',
    },
  };

  static String getString(String key, String languageCode) {
    return _strings[languageCode]?[key] ?? _strings['en']![key] ?? key;
  }

  static String getStringWithFallback(String key, String languageCode) {
    final translation = _strings[languageCode]?[key];
    if (translation != null) return translation;

    final englishFallback = _strings['en']?[key];
    if (englishFallback != null) return englishFallback;

    return key;
  }
}
